import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Render from './Render'
import styled, { ThemeProvider } from "styled-components";
import DarkThemeProvider from "./DarkThemeProvider";
import Vision from './home/Vision'
import NavBar from './home/components/NavBar/NavBar'
import MainPage from './home/MainPage'
import Testimonials from './home/Testimonials';
import Projects from './home/Projects';
import WhyChooseUs from './home/WhyChooseUs';

export default function Home() {
  return (
    <div>

      {/* className={styles.container} */}
      {/* <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
     
    </main>

    <footer className={styles.footer}>
      
    </footer> */}
      {/* <NavBar /> */}
      {/* <Render /> */}
      <NavBar />
      <MainPage />
      <Vision />
      <Testimonials />
      <Projects />
      <WhyChooseUs />

    </div>
  )
}
